# Generated by Django 4.2.8 on 2023-12-10 15:02
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255,
                        verbose_name='Contract title',
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255,
                        verbose_name='Loan application title',
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                (
                    'contract',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='loan_application',
                        to='testapp.contract',
                        verbose_name='Contract',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Loan application',
                'verbose_name_plural': 'Loan applications',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        verbose_name='Manufacturer name',
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        verbose_name='Product name',
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                (
                    'loan_application',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='product',
                        to='testapp.loanapplication',
                        verbose_name='Loan application',
                    ),
                ),
                (
                    'manufacturer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='product',
                        to='testapp.manufacturer',
                        verbose_name='Manufacturer',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
